version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: hex_db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=banking
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./setup/setup.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local